import { Inter } from "next/font/google";
import Head from "next/head";

import { trpc } from "~/lib/trpc";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data } = trpc.entries.get.useQuery();
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}></main>
    </>
  );
}
